apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ .Values.deployment.name }}-cm
  namespace: {{ .Values.namespace }}
data:
  {{- range $k, $v := .Values.appConfiguration }}
  {{$k}}: "{{$v}}"
  {{- end }}